Modulize project and add readinfo
JuliaSparse/MatrixMarket.jl pull request #51
Opened 2023-02-03 05:39 UTC by yuehhua

Separated from #50

2023-02-03 14:08 UTC, tkonolige commented
If I understand correctly, this PR does three things: 1. it splits the single file into multiple different files 2. it rewrites the parser and 3. it changes `readinfo` from a flag to a separate function.

Can you explain the purpose behind why you split the code into multiple files? From an organizational perspective, a single file seems fine for me. Is there a different reason to do the split?

Can you explain why you rewrote the parser? Did you add support for more features?

Regarding `readinfo` is there a reason to move it to a separate function instead of a flag? I'd prefer not to change the api unless we have to. It causes unnecessary churn for users.

2023-02-03 15:38 UTC, yuehhua commented
> 1. it splits the single file into multiple different files

Originally, the functionality is focusing on `mmread` and `mmwrite` over a file. This contains several functionalities in parsing, identifying matrix and generating outcomes in one jumbled function. This makes it an obstacle from readability, feature extensibility, usage flexibility and testing. Splitting single file into multiple different files removes this obstacle to achieve those benefits by managing different functionalities on its own file. Thus, different functionalities could be extended independently.

> 2. it rewrites the parser

Following the reason above, a jumbled function contains functionalities in parsing, identifying matrix and generating outcomes. It couples tightly between different functionalities. Actually, all I did is to reorganize code and keep the logic the same. Maybe a little part of code seems be rewritten. No new feature is introduced.

> 3. it changes `readinfo` from a flag to a separate function.

Although a flag is enough for reading header information form a file, a specialized function situates its responsibility properly and this fullfills single-responsibility principle. In other languages, like [Python](https://docs.scipy.org/doc/scipy/reference/io.html#matrix-market-files) or [MATLAB](https://math.nist.gov/MatrixMarket/mmio/matlab/mmiomatlab.html), they also provide `mminfo` for extracting size and storage information. Uh...........so maybe I should follow the convention and rename `readinfo` to `mminfo`?

2023-02-04 23:19 UTC, tkonolige requested changes
Could you add back the `infoonly` flag to `mmread` so that we don't break existing code.

2023-02-04 23:19 UTC, tkonolige commented on src/generate.jl
> +generate_eltype(::Type{<:Bool}) = "pattern"
This file is pretty small, might as well move it into the same file as mmwrite.

2023-02-04 23:19 UTC, tkonolige commented on src/matrix.jl
> +function hermitianize!(M::AbstractMatrix)
Move these into the file in which they are used.

2023-02-04 23:19 UTC, tkonolige commented on src/parse.jl
> +function parse_eltype(field::String)
Move this file into the file containing `mmread`.

2023-02-04 23:19 UTC, tkonolige commented on src/utils.jl
> +struct FileFormatException <: Exception
Move this file into the file in which it is used.

2023-02-05 12:04 UTC, yuehhua commented on src/generate.jl
> +generate_eltype(::Type{<:Bool}) = "pattern"
Done.

2023-02-05 12:04 UTC, yuehhua commented on src/matrix.jl
> +function hermitianize!(M::AbstractMatrix)
Done.

2023-02-05 12:04 UTC, yuehhua commented on src/generate.jl
> +generate_eltype(::Type{<:Bool}) = "pattern"
Done.

2023-02-06 01:36 UTC, tkonolige commented on test/runtests.jl
> -@testset "Idempotent IO" begin
Looks like you deleted this test

2023-02-06 02:36 UTC, yuehhua commented on test/runtests.jl
> -@testset "Idempotent IO" begin
Should be covered by testing `mmread`: https://github.com/JuliaSparse/MatrixMarket.jl/pull/51/files#diff-757c8c3ea9ad9fdbf9762105164f634888fd765b0e5c050c3c420036b522e3f1R29
and `mmwrite`: https://github.com/JuliaSparse/MatrixMarket.jl/pull/51/files#diff-757c8c3ea9ad9fdbf9762105164f634888fd765b0e5c050c3c420036b522e3f1R32-R42

2023-02-06 02:39 UTC, yuehhua commented on test/runtests.jl
> -@testset "Idempotent IO" begin
Unit test here checks not only idempotent property but more general reading and writing .mtx file equivalence as well as examining sparse matrix equivalence.

2023-02-06 02:46 UTC, yuehhua commented
Currently, basic reading and writing sparse matrix (with `coordinate`) are supported. On the other hand, reading and writing dense matrix (with `array`) from .mtx file is not supported, since the original version of `mmwrite` [hard coded](https://github.com/JuliaSparse/MatrixMarket.jl/pull/51/files#diff-5973445353ef02c27c657ef19eb9b9ac2f3fee985a64f341c21202636235b853R23) writing only "coordinate" to .mtx file. The original version doesn't have full support on all .mtx format and we could work on this in the near future.

2023-02-06 03:27 UTC, tkonolige commented on test/runtests.jl
> -@testset "Idempotent IO" begin
That test is only testing the single test matrix you provide. We want to test more from the provided collection.

2023-02-06 05:31 UTC, yuehhua commented on test/runtests.jl
> -@testset "Idempotent IO" begin
Done.

2023-02-06 17:02 UTC, tkonolige commented on test/mtx.jl
> +                url = "ftp://math.nist.gov/pub/MatrixMarket2/$collectionname/$setname/$matrixname.mtx.gz"
```suggestion
                url = "https://math.nist.gov/pub/MatrixMarket2/$collectionname/$setname/$matrixname.mtx.gz"
```
Seems like the tests won't work otherwise.

2023-02-07 02:45 UTC, tkonolige approved these changes
Thanks @yuehhua!

2023-02-07 02:45 UTC, merged